name: Deploy
on: workflow_dispatch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version-file: ".nvmrc"
          cache: "npm"

      - name: Install dependencies and build
        run: |
          npm ci
          npm run build

      - name: Deploy to Firebase
        run: |
          npx firebase-tools deploy --token "${{ secrets.FIREBASE_TOKEN }}" --project joebrown-dev --json
